weatherAPI/urls.py
from django.urls import path
from . import views

app_name = "weather_api"
urlpatterns = [
    path("",views.WeatherCheckView,name="WeatherCheck"),
    path("404/",views.Handler404,name="handler404"),
]

web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('weatherAPI.urls'))
]

weatherAPI/models.py
from django.db import models

# Create your models here.

weatherAPI/views.py
from http.client import BAD_REQUEST
from django.shortcuts import render,redirect
from urllib.request import urlopen
import json
from datetime import datetime as dt
from pytz import timezone
from urllib.error import URLError, HTTPError
# Create your views here.
def WeatherCheckView(request):

    # Fetching data from openweather site
    url = 'https://api.openweathermap.org/data/2.5/weather?q='
    apiKey = '6d4ad160fe4f3b48806166fba0ec988e'

    # Using ip finder site
    IP_Finder_Source = urlopen("http://ipinfo.io/json").read()

    # Show the weather by user location
    IP_Finder = json.loads(IP_Finder_Source)
    
    try:

        if request.method == "POST":
            city = request.POST.get('city',IP_Finder['city'])
    
            if city.isdigit():
                city = IP_Finder['city']
            data = urlopen(url+city+"&appid="+apiKey).read()
            data = json.loads(data)
            # Current day
            today = dt.now().strftime("%A")

            country = data['sys']['country']

            context = {

            "today":today,

            "country":country,
            "city":city,

            # converting to celsius
            "temperature":int(data['main']['temp']-273.15),

            # Coordinate point
            "coordinate":data['coord'],
            
            "main":data['main'],
            "weather":data['weather'],

            }
        else:
            # First we save timezone then take the data and time
            time_zone = timezone(IP_Finder['timezone'])

            # Current day
            today = dt.now().strftime("%A")

            #Current date
            date = dt.now().strftime("%B %d, %Y")

            # Showing time based on user timezone
            DateTime = dt.now(time_zone).strftime('%H:%M:%S')

            # Getting city and country by IP.
            city = IP_Finder['city']
            country = IP_Finder['country']

            data = urlopen(url+city+"&appid="+apiKey).read()

            # Convert the source code to json
            data = json.loads(data)

            context = {

                "today":today,

                "current_date":date,

                "DateTime":DateTime ,


                "country":country,
                "city":city,

                # converting to celsius
                "temperature":int(data['main']['temp']-273.15),

                # Coordinate point
                "coordinate":data['coord'],
                
                "main":data['main'],
                "weather":data['weather'],

            }
        return render(request,'weatherAPI/weather.html',context)
    except HTTPError as e:
        if e.code == 404:
            return redirect('weather_api:handler404')
    
def Handler404(request):
    return render(request,'weatherAPI/handler404.html',context={})

weatherAPI/templates/weatherAPI/handler404.html
<!DOCTYPE html>
<html lang="en">


    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bootstrap 5 404 Error Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>


    <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    The country or city you’re looking for doesn’t exist.
                  </p>
                <a href=" {% url 'weather_api:WeatherCheck' %} " class="btn btn-primary">Go Home</a>
            </div>
        </div>
    </body>


</html>

weatherAPI/templates/weatherAPI/weather.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>Document</title>
  </head>
  <body>
    
    <div class="page-content page-container" id="page-content">
      <div class="padding">
        <div class="row container d-flex justify-content-center">
          <div class="col-lg-8 grid-margin stretch-card">
           
            <!--weather card-->
            {% if city and country and temperature and weather and coordinate %}
            <div class="card card-weather">
              <div class="card-body">
                <div class="weather-date-location">
                  <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" name="city" required>
                    <button class="btn btn-primary" type="submit" >Search</button>
                  </form>
                  <h3>{{today}}</h3>
                  <h4>{{current_date}}</h4>
                  <p class="text-gray">
                    <span class="weather-location">{{city}} {{country}}</span><br>
                    <span class="weather-date">{{DateTime}}</span>
                  </p>
                </div>
                <div class="weather-data d-flex">
                  <div class="mr-auto">
                    <h4 class="display-3">
                      {{temperature}} <span class="symbol">&deg;</span>C <br />
                    </h4>
                    <div style="display: flex; ">
                      <h4>{{weather.0.main}} : {{weather.0.description}}</h4>
                      <img
                        src="http://openweathermap.org/img/wn/{{weather.0.icon}}.png"
                        alt="Img"
                      />
                    </div>
                    <p>
                      Latitude : {{coordinate.lat}} <br />
                      Longitude : {{coordinate.lon}}
                    </p>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
            <!--weather card ends-->
          </div>
        </div>
      </div>
    </div>
  </body>
</html>